// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RecollectionMode","status":true,"description":"回想モード機能を追加します。","parameters":{}},
{"name":"RecollectionMode_through_command_patch","status":true,"description":"RecollectionModeのパッチです。タイトルから直接回想閲覧に遷移します","parameters":{}},
{"name":"RecollectionMode_save_switch_patch","status":true,"description":"セーブデータに、その時点のスイッチ情報を保存することができます。","parameters":{}},
{"name":"RecollectionMode_through_command_cg_only_patch","status":false,"description":"RecollectionModeのパッチです。タイトルから直接CG閲覧に遷移します","parameters":{}}
];
